[package]
name = "inchworm"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
hex = "0.4"
serde_json = "1"
bincode = "1"
serde = { version = "1", features = ["derive"] }
memmap2 = "0.5"


[[bin]]
name = "gloss_tool"
path = "src/bin/gloss_tool.rs"

[[bin]]
name = "compressor"
path = "src/bin/compressor.rs"

[[bin]]
name = "hash_precompute"
path = "src/bin/hash_precompute.rs"
