//! Multi-pass compression tests.
//! Uses Blake3Expander (same as default Config) to generate structured data.
use telomere::hasher::{Blake3Expander, SeedExpander};
use telomere::{compress_multi_pass_with_config, compress_with_run_summary, decompress, Config};

fn fast_cfg(block_size: usize) -> Config {
    Config {
        block_size,
        max_seed_len: 1,
        hash_bits: 13,
        ..Config::default()
    }
}

fn expand(seed: &[u8], len: usize) -> Vec<u8> {
    let mut out = vec![0u8; len];
    Blake3Expander.expand_into(seed, &mut out);
    out
}

#[test]
fn multi_pass_converges_without_gain() {
    // Data with no compressive seeds: second pass should find nothing new.
    let cfg = fast_cfg(3);
    let data: Vec<u8> = (0u8..30).collect();
    let (out1, _) = compress_multi_pass_with_config(&data, &cfg, 1, false).unwrap();
    let (out2, _) = compress_multi_pass_with_config(&data, &cfg, 5, false).unwrap();
    // Multiple passes shouldn't produce a larger result than one pass.
    assert!(out2.len() <= out1.len());
}

#[test]
fn multi_pass_roundtrip_literal_data() {
    // With no seed matches, everything is literal — roundtrip must still hold.
    let cfg = fast_cfg(4);
    let data: Vec<u8> = (0u8..40).collect();
    let (compressed, _) = compress_multi_pass_with_config(&data, &cfg, 3, false).unwrap();
    let decoded = decompress(&compressed, &cfg).expect("decompress failed");
    assert_eq!(decoded, data);
}

#[test]
fn multi_pass_roundtrip_structured_data() {
    // Data generated by BLAKE3([0x00]): the compressor can find 1-byte seed matches.
    let cfg = fast_cfg(1);
    let data = expand(&[0x00], 8);
    let (compressed, _) = compress_multi_pass_with_config(&data, &cfg, 3, false).unwrap();
    let decoded = decompress(&compressed, &cfg).expect("decompress failed");
    assert_eq!(decoded, data);
}

#[test]
fn multi_pass_repetitive_data_roundtrip() {
    // Repetitive data: same block repeated — bundling should amortize header.
    let cfg = fast_cfg(1);
    let block = expand(&[0x01], 1);
    let data: Vec<u8> = block.iter().cloned().cycle().take(8).collect();
    let (compressed, _) = compress_multi_pass_with_config(&data, &cfg, 3, false).unwrap();
    let decoded = decompress(&compressed, &cfg).expect("decompress failed");
    assert_eq!(decoded, data);
}

#[test]
fn run_summary_has_correct_structure() {
    let cfg = fast_cfg(1);
    let data = expand(&[0x00], 8);
    let (best, summary) = compress_with_run_summary(&data, &cfg, 5).unwrap();
    // Summary must have at least 1 pass.
    assert!(!summary.passes.is_empty());
    // Best output must at least contain TlmrHeader (3 bytes).
    assert!(best.len() >= 3);
    // JSON must be valid.
    let json = summary.to_json();
    assert!(json.contains("passes"));
    assert!(json.contains("original_bytes"));
    // Verify roundtrip with the best output.
    let decoded = decompress(&best, &cfg).expect("decompress best failed");
    assert_eq!(decoded, data);
}

#[test]
fn run_summary_delta_measurement() {
    // For known-seed data, verify that delta measurement tracks bytes correctly.
    let cfg = fast_cfg(1);
    let data = expand(&[0x00], 4); // 4 one-byte blocks
    let (_out, summary) = compress_with_run_summary(&data, &cfg, 3).unwrap();
    let first = &summary.passes[0];
    assert_eq!(first.bytes_in, data.len(), "pass 1 input = original data size");
    assert_eq!(first.pass, 1);
}
