#!/usr/bin/env python3
"""Lightweight documentation consistency checks for the current Telomere docs."""

from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


REQUIRED_FILES = [
    "README.md",
    "docs/ARCHITECTURE.md",
    "docs/FORMAT.md",
    "docs/RESULTS.md",
    "docs/results.json",
    "docs/TOOLS.md",
    "docs/RELEASE_CHECKLIST.md",
]

README_REQUIRED = [
    "--json",
    "--verify",
    "--hasher",
    "--memory-limit",
    "--force",
    ".tlmr",
    "seed depth 1",
    "seed depth 2",
    "seed depth 3",
]

FORMAT_REQUIRED = [
    "hasher_kind",
    "lotus_preset",
    "layer_count",
    "arity `2` is valid",
    "non-byte-aligned seed payloads are rejected",
]

FORBIDDEN_PHRASES = [
    "arity 2 is reserved",
    "reserved for literal marker",
    "random data should compress",
    "guarantee compression",
    "recursive convergence goal",
]


def fail(msg: str) -> None:
    print(f"ERROR: {msg}")
    sys.exit(1)


def read(path: str) -> str:
    full = ROOT / path
    if not full.exists():
        fail(f"missing required doc {path}")
    return full.read_text(encoding="utf-8")


def main() -> None:
    texts = {path: read(path) for path in REQUIRED_FILES}

    readme_lower = texts["README.md"].lower()
    for phrase in README_REQUIRED:
        if phrase not in readme_lower:
            fail(f"README.md missing {phrase}")

    format_lower = texts["docs/FORMAT.md"].lower()
    for phrase in FORMAT_REQUIRED:
        if phrase not in format_lower:
            fail(f"docs/FORMAT.md missing {phrase}")

    for path, text in texts.items():
        lower = text.lower()
        for phrase in FORBIDDEN_PHRASES:
            if phrase in lower:
                fail(f"{path} contains stale phrase: {phrase}")

    results = json.loads(texts["docs/results.json"])
    if results.get("generated_by") != "scripts/generate_results.py":
        fail("docs/results.json is not marked as generated by scripts/generate_results.py")
    if not results.get("results"):
        fail("docs/results.json contains no result rows")

    for test_file in (ROOT / "tests").rglob("*.rs"):
        if "#[ignore" in test_file.read_text(encoding="utf-8"):
            fail(f"{test_file.relative_to(ROOT)} contains #[ignore]")

    if (ROOT / "error.log").exists():
        fail("tracked junk artifact error.log still exists")

    print("Doc lint passed")


if __name__ == "__main__":
    main()
