#!/usr/bin/env python3
"""Generate Telomere acceleration/GPU readiness report."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
REPORT_JSON = DOCS / "acceleration_report.json"
REPORT_MD = DOCS / "ACCELERATION.md"

SOURCE_FILES = [
    "Cargo.toml",
    "src/block.rs",
    "src/gpu.rs",
    "src/gpu_cpu.rs",
    "src/gpu_impl.rs",
    "src/gpu_kernels.cl",
    "src/hybrid.rs",
    "src/kernels/seed_match.cl",
    "tests/gpu_determinism.rs",
    "tests/gpu_tiling.rs",
    "tests/hybrid_match.rs",
]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def sha256(path: str) -> str:
    return hashlib.sha256((ROOT / path).read_bytes()).hexdigest()


def command_status(cmd: list[str]) -> dict[str, Any]:
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    return {
        "cmd": " ".join(cmd),
        "exit_code": proc.returncode,
        "stdout_tail": proc.stdout[-1200:],
        "stderr_tail": proc.stderr[-1200:],
    }


def detect_status() -> dict[str, Any]:
    cargo = read("Cargo.toml")
    gpu_rs = read("src/gpu.rs")
    gpu_impl = read("src/gpu_impl.rs")
    gpu_cpu = read("src/gpu_cpu.rs")
    gpu_kernels = read("src/gpu_kernels.cl")
    seed_match_kernel = read("src/kernels/seed_match.cl")
    parity_test = read("tests/gpu_determinism.rs")

    has_gpu_feature = 'gpu = ["ocl"]' in cargo
    research_only = "research-only" in gpu_rs.lower() and "research-only" in gpu_impl.lower()
    cpu_semantics = "deterministic CPU" in gpu_rs or "CPU implementation" in gpu_cpu
    parity_guard = "canonical CPU seed search" in parity_test and "GpuSeedMatcher" in parity_test
    real_kernel_markers = ("Kernel::builder", "__kernel", "Program::builder")
    has_real_kernel = any(marker in gpu_impl for marker in real_kernel_markers)
    kernel_source_files_present = "__kernel" in gpu_kernels or "__kernel" in seed_match_kernel

    status = "research-only-cpu-semantics"
    production_ready = False
    blockers = [
        "No OpenCL/CUDA kernel-backed matcher is implemented.",
        "Tracked kernel prototypes are source-hashed but are not wired into the matcher.",
        "No hardware benchmark shows GPU beats CPU streaming.",
        "Only small CPU/GPU API parity guards exist today.",
    ]

    return {
        "feature_declared": has_gpu_feature,
        "research_only_docs": research_only,
        "cpu_semantics_backend": cpu_semantics,
        "parity_guard_present": parity_guard,
        "kernel_source_files_present": kernel_source_files_present,
        "real_kernel_detected": has_real_kernel,
        "status": status,
        "production_ready": production_ready,
        "blockers": blockers,
    }


def build_report(run_checks: bool) -> dict[str, Any]:
    source_hashes = {path: sha256(path) for path in SOURCE_FILES}
    report = {
        "generated_by": "scripts/generate_acceleration_report.py",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "format_version": 1,
        "source_hashes": source_hashes,
        "detected": detect_status(),
        "checks": [],
        "promotion_criteria": [
            "Implement a real hardware backend with explicit kernel/device code.",
            "Keep CPU/GPU byte-for-byte parity tests for selected spans and decompressed output.",
            "Benchmark against CPU streaming on planted, structured, random, and corpus-matrix controls.",
            "Show a measured speed or energy win before calling GPU production.",
            "Document device requirements, fallback behavior, and failure modes.",
        ],
    }
    if run_checks:
        report["checks"] = [
            command_status(["cargo", "check", "--features", "gpu", "--all-targets"]),
            command_status(["cargo", "test", "--test", "gpu_determinism"]),
            command_status(["cargo", "test", "--test", "gpu_tiling"]),
            command_status(["cargo", "test", "--test", "hybrid_match"]),
        ]
    return report


def write_report(payload: dict[str, Any]) -> None:
    REPORT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    detected = payload["detected"]
    lines = [
        "# Telomere Acceleration Report",
        "",
        "Generated by `scripts/generate_acceleration_report.py` from current source and optional checks.",
        "",
        f"Status: **{detected['status']}**.",
        f"Production ready: **{str(detected['production_ready']).lower()}**.",
        "",
        "## Detected Surface",
        "",
        f"- GPU feature declared: `{detected['feature_declared']}`",
        f"- Research-only docs present: `{detected['research_only_docs']}`",
        f"- CPU-semantics backend: `{detected['cpu_semantics_backend']}`",
        f"- Parity guard present: `{detected['parity_guard_present']}`",
        f"- Kernel source files present: `{detected['kernel_source_files_present']}`",
        f"- Real kernel detected: `{detected['real_kernel_detected']}`",
        "",
        "## Blockers",
        "",
    ]
    lines.extend(f"- {blocker}" for blocker in detected["blockers"])

    lines.extend(["", "## Promotion Criteria", ""])
    lines.extend(f"- {item}" for item in payload["promotion_criteria"])

    if payload["checks"]:
        lines.extend(["", "## Checks", ""])
        for check in payload["checks"]:
            lines.append(f"- `{check['cmd']}` exit `{check['exit_code']}`")

    lines.extend(["", "## Source Hashes", ""])
    for path, digest in payload["source_hashes"].items():
        lines.append(f"- `{path}`: `{digest}`")

    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def check_report() -> None:
    if not REPORT_JSON.exists() or not REPORT_MD.exists():
        raise SystemExit("generated acceleration report files are missing")
    payload = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    if payload.get("generated_by") != "scripts/generate_acceleration_report.py":
        raise SystemExit("acceleration_report.json has wrong generated_by marker")
    expected_hashes = {path: sha256(path) for path in SOURCE_FILES}
    if payload.get("source_hashes") != expected_hashes:
        raise SystemExit("acceleration report source hashes are stale")
    detected = payload.get("detected", {})
    if detected.get("production_ready") is not False:
        raise SystemExit("acceleration report must not claim production readiness")
    text = REPORT_MD.read_text(encoding="utf-8")
    for phrase in ("research-only-cpu-semantics", "Real kernel detected", "Promotion Criteria"):
        if phrase not in text:
            raise SystemExit(f"ACCELERATION.md missing phrase: {phrase}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate generated acceleration report")
    parser.add_argument("--run-checks", action="store_true", help="include cargo GPU/parity checks in the report")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.check:
        check_report()
        return
    write_report(build_report(run_checks=args.run_checks))


if __name__ == "__main__":
    main()
