#!/usr/bin/env python3
"""Summarize frozen public-preset package-accounting experiments.

The heavy experiment runner writes detailed rows under target/thesis_runs.
This helper distills those measured outputs into a small checked artifact so
package-level accounting does not get confused with per-file standalone
accounting again.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RUN_DIR = ROOT / "target" / "thesis_runs" / "frozen_codebook_experiment"
OUT_JSON = ROOT / "docs" / "public_preset_package_accounting.json"
OUT_MD = ROOT / "docs" / "PUBLIC_PRESET_PACKAGE_ACCOUNTING.md"

RUNS = [
    {
        "id": "calgary_to_canterbury_tokens32",
        "path": RUN_DIR / "calgary_to_canterbury_tokens32_package_accounting.json",
        "role": "best compact Canterbury package run",
    },
    {
        "id": "calgary_to_canterbury_train_greedy_pool128",
        "path": RUN_DIR / "calgary_to_canterbury_train_greedy_pool128_package_accounting.json",
        "role": "training-greedy Canterbury comparison",
    },
    {
        "id": "calgary_to_canterbury_joint_marginal_pool8",
        "path": RUN_DIR / "calgary_to_canterbury_joint_marginal_pool8_package_accounting.json",
        "role": "joint-marginal Canterbury falsification probe",
    },
    {
        "id": "calgary_to_canterbury_tokens128",
        "path": RUN_DIR / "calgary_to_canterbury_package_accounting.json",
        "role": "larger-table Canterbury comparison",
    },
    {
        "id": "calgary_to_silesia_under7mb_tokens64",
        "path": RUN_DIR / "calgary_to_silesia_under7mb_tokens64_package_accounting.json",
        "role": "best compact Silesia under-7MB package run",
    },
    {
        "id": "calgary_to_silesia_under7mb_train_greedy_pool128",
        "path": RUN_DIR
        / "calgary_to_silesia_under7mb_train_greedy_pool128_package_accounting.json",
        "role": "training-greedy Silesia under-7MB comparison",
    },
    {
        "id": "calgary_to_silesia_under7mb_joint_marginal_pool8",
        "path": RUN_DIR
        / "calgary_to_silesia_under7mb_joint_marginal_pool8_package_accounting.json",
        "role": "joint-marginal Silesia under-7MB falsification probe",
    },
    {
        "id": "calgary_to_silesia_under7mb_tokens128",
        "path": RUN_DIR / "calgary_to_silesia_under7mb_package_accounting.json",
        "role": "larger-table Silesia under-7MB comparison",
    },
]


SUMMARY_KEYS = [
    "input_bytes",
    "files",
    "codebook_bytes_json_compact",
    "framed_delta_bytes",
    "inner_tlmr_delta_bytes",
    "fully_charged_package_bytes",
    "fully_charged_package_delta_bytes",
    "fully_charged_package_ratio",
    "standalone_fully_charged_sum_delta_bytes",
    "selected_count",
    "token_replacements",
    "inverse_failures",
    "telomere_failures",
]


def load_run(item: dict[str, Any]) -> dict[str, Any]:
    if not item["path"].exists():
        raise FileNotFoundError(
            f"missing {item['path']}; run scripts/run_frozen_codebook_experiment.py first"
        )
    payload = json.loads(item["path"].read_text(encoding="utf-8"))
    summary = payload["summary"]
    variants = payload.get("variant_comparison", [])
    seed_alignment = payload.get("seed_alignment_control_deltas", [])
    controls = [
        {
            "variant": row["variant"],
            "fully_charged_delta_bytes": row.get("fully_charged_delta_bytes"),
            "selected_count": row.get("selected_count"),
        }
        for row in variants
        if row.get("variant") != "real"
    ]
    best_seed_dividend = None
    for row in seed_alignment:
        value = row.get("real_minus_control_fully_charged_package_bytes")
        if value is None:
            continue
        if best_seed_dividend is None or value < best_seed_dividend:
            best_seed_dividend = value
    return {
        "id": item["id"],
        "role": item["role"],
        "source": str(item["path"].relative_to(ROOT)).replace("\\", "/"),
        "summary": {key: summary.get(key) for key in SUMMARY_KEYS},
        "controls": controls,
        "seed_alignment_dividend_bytes_vs_best_control": best_seed_dividend,
    }


def write_markdown(payload: dict[str, Any]) -> None:
    rows = payload["runs"]
    lines = [
        "# Public Preset Package Accounting",
        "",
        "Generated by `scripts/generate_public_preset_package_accounting.py` from measured `target/thesis_runs` outputs.",
        "",
        "Package accounting charges the frozen public codebook once per evaluated package. Per-file standalone accounting remains reported separately.",
        "",
        "| Run | Input | Codebook | Selected spans | Full package delta | Standalone sum delta | Best seed dividend vs control |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        summary = row["summary"]
        lines.append(
            "| {id} | {input_bytes} | {codebook} | {selected} | {delta} | {standalone} | {dividend} |".format(
                id=row["id"],
                input_bytes=summary["input_bytes"],
                codebook=summary["codebook_bytes_json_compact"],
                selected=summary["selected_count"],
                delta=summary["fully_charged_package_delta_bytes"],
                standalone=summary["standalone_fully_charged_sum_delta_bytes"],
                dividend=row["seed_alignment_dividend_bytes_vs_best_control"],
            )
        )
    lines.extend(
        [
            "",
            "Control interpretation:",
            "",
            "- `random-codeword` and `out-of-budget-codeword` preserve replacement positions but remove seed-addressable codewords.",
            "- If a control is negative, that is dictionary-transform compression, not Telomere seed compression.",
            "- The seed thesis contribution is the additional byte delta of the real seed-codeword run versus those controls, with selected spans present only in the real run.",
            "",
        ]
    )
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    runs = [load_run(item) for item in RUNS]
    payload = {
        "generated_by": "scripts/generate_public_preset_package_accounting.py",
        "source_experiment": "scripts/run_frozen_codebook_experiment.py",
        "claim_boundary": (
            "non-planted public-preset package evidence; not a finalized .tlmr "
            "format extension or universal natural-corpus compression claim"
        ),
        "accounting_rule": "charge frozen public codebook once per evaluated package",
        "runs": runs,
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    write_markdown(payload)
    print(f"WROTE {OUT_JSON}")
    print(f"WROTE {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
