#!/usr/bin/env python3
"""Capture fresh release-candidate command output for Telomere.

The production proof matrix is intentionally conservative: generated ledgers
can describe required gates, but release candidates still need command output
from the exact tree being considered. This script runs those commands, stores
their logs, and writes a small generated proof artifact that other ledgers can
validate without rerunning the commands.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
REPORT_JSON = DOCS / "candidate_runtime_verification.json"
REPORT_MD = DOCS / "CANDIDATE_RUNTIME_VERIFICATION.md"
LOG_DIR = DOCS / "candidate_runtime_verification"
GENERATED_BY = "scripts/generate_candidate_runtime_verification.py"

REQUIRED_RELEASE_COMMANDS = [
    "cargo fmt --all -- --check",
    "cargo fmt --manifest-path src-tauri/Cargo.toml -- --check",
    "cargo clippy --all-targets -- -D warnings",
    "cargo test --all-targets",
    "cargo check --features gpu --all-targets",
    "cargo check --manifest-path src-tauri/Cargo.toml",
    "cargo test --manifest-path src-tauri/Cargo.toml",
    "python scripts/doc_lint.py",
    "python scripts/generate_evidence_regimen.py --check",
    "python scripts/generate_research_ledgers.py --check",
]

INCLUDED_SNAPSHOT_ROOTS = [
    ".github",
    "AGENTS.md",
    "Cargo.lock",
    "Cargo.toml",
    "README.md",
    "RESEARCH_PLAN.md",
    "TASK_CHECKLIST.md",
    "corpora",
    "docs",
    "scripts",
    "src",
    "src-tauri/Cargo.toml",
    "src-tauri/src",
    "src-tauri/tauri.conf.json",
    "tests",
    "ui",
]

EXCLUDED_DIR_NAMES = {
    ".git",
    ".serena",
    "__pycache__",
    "candidate_runtime_verification",
    "node_modules",
    "target",
}

EXCLUDED_RELATIVE_FILES = {
    "docs/BLOCKED_REQUIREMENT_DISPATCH.md",
    "docs/CANDIDATE_RUNTIME_VERIFICATION.md",
    "docs/GOAL_COMPLETION_AUDIT.md",
    "docs/PRODUCTION_PROOF_MATRIX.md",
    "docs/blocked_requirement_dispatch.json",
    "docs/candidate_runtime_verification.json",
    "docs/goal_completion_audit.json",
    "docs/production_proof_matrix.json",
}


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def iso(value: datetime) -> str:
    return value.isoformat()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(data: str) -> str:
    return sha256_bytes(data.encode("utf-8", errors="replace"))


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def command_manifest_hash() -> str:
    payload = json.dumps(REQUIRED_RELEASE_COMMANDS, separators=(",", ":"), sort_keys=True)
    return sha256_text(payload)


def should_skip(path: Path) -> bool:
    rel = relative(path)
    if rel in EXCLUDED_RELATIVE_FILES:
        return True
    return any(part in EXCLUDED_DIR_NAMES for part in path.relative_to(ROOT).parts)


def is_generated_doc(path: Path) -> bool:
    if not path.is_relative_to(DOCS) or path.suffix.lower() not in {".json", ".md"}:
        return False
    try:
        prefix = path.read_text(encoding="utf-8", errors="replace")[:512]
    except OSError:
        return False
    return (
        '"generated_by": "scripts/generate_' in prefix
        or "Generated by `scripts/generate_" in prefix
    )


def iter_snapshot_files() -> list[Path]:
    files: list[Path] = []
    for item in INCLUDED_SNAPSHOT_ROOTS:
        path = ROOT / item
        if not path.exists():
            continue
        if path.is_file():
            if not should_skip(path) and not is_generated_doc(path):
                files.append(path)
            continue
        for candidate in path.rglob("*"):
            if (
                candidate.is_file()
                and not should_skip(candidate)
                and not is_generated_doc(candidate)
            ):
                files.append(candidate)
    return sorted(set(files), key=lambda value: relative(value))


def workspace_snapshot() -> dict[str, Any]:
    entries = [
        {"path": relative(path), "sha256": sha256_file(path)}
        for path in iter_snapshot_files()
    ]
    manifest = json.dumps(entries, separators=(",", ":"), sort_keys=True)
    return {
        "included_roots": INCLUDED_SNAPSHOT_ROOTS,
        "excluded_dir_names": sorted(EXCLUDED_DIR_NAMES),
        "excluded_relative_files": sorted(EXCLUDED_RELATIVE_FILES),
        "file_count": len(entries),
        "snapshot_sha256": sha256_text(manifest),
    }


def slug(command: str) -> str:
    cleaned = []
    for char in command.lower():
        if char.isalnum():
            cleaned.append(char)
        elif cleaned and cleaned[-1] != "-":
            cleaned.append("-")
    return "".join(cleaned).strip("-")[:72] or "command"


def run_command(index: int, command: str) -> dict[str, Any]:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    started = utc_now()
    completed = subprocess.run(
        command,
        cwd=ROOT,
        shell=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env={**os.environ, "CARGO_TERM_COLOR": "never"},
    )
    finished = utc_now()
    log_rel = f"docs/candidate_runtime_verification/{index:02d}-{slug(command)}.txt"
    log_path = ROOT / log_rel
    body = "\n".join(
        [
            f"command: {command}",
            f"started_at: {iso(started)}",
            f"finished_at: {iso(finished)}",
            f"returncode: {completed.returncode}",
            "",
            "----- stdout -----",
            completed.stdout,
            "",
            "----- stderr -----",
            completed.stderr,
            "",
        ]
    )
    log_path.write_text(body, encoding="utf-8")
    output = completed.stdout + completed.stderr
    return {
        "index": index,
        "command": command,
        "returncode": completed.returncode,
        "passed": completed.returncode == 0,
        "started_at": iso(started),
        "finished_at": iso(finished),
        "duration_seconds": round((finished - started).total_seconds(), 3),
        "stdout_bytes": len(completed.stdout.encode("utf-8", errors="replace")),
        "stderr_bytes": len(completed.stderr.encode("utf-8", errors="replace")),
        "output_sha256": sha256_text(output),
        "log_path": log_rel,
        "log_sha256": sha256_file(log_path),
        "stdout_tail": completed.stdout[-1200:],
        "stderr_tail": completed.stderr[-1200:],
    }


def build_report(run_commands: bool) -> dict[str, Any]:
    started = utc_now()
    snapshot = workspace_snapshot()
    commands = (
        [run_command(index, command) for index, command in enumerate(REQUIRED_RELEASE_COMMANDS, 1)]
        if run_commands
        else []
    )
    finished = utc_now()
    passed_count = sum(1 for command in commands if command.get("passed"))
    failed = [command for command in commands if not command.get("passed")]
    all_passed = run_commands and not failed and len(commands) == len(REQUIRED_RELEASE_COMMANDS)
    return {
        "generated_by": GENERATED_BY,
        "generated_at": iso(finished),
        "format_version": 1,
        "scope": {
            "kind": "candidate runtime verification",
            "runs_release_commands": run_commands,
            "performs_seed_search": False,
            "makes_compression_claim": False,
            "marks_production_ready": False,
        },
        "command_manifest_sha256": command_manifest_hash(),
        "workspace_snapshot": snapshot,
        "summary": {
            "runtime_status": "passed" if all_passed else "failed",
            "all_required_commands_passed": all_passed,
            "command_count": len(REQUIRED_RELEASE_COMMANDS),
            "executed_command_count": len(commands),
            "passed_count": passed_count,
            "failed_count": len(failed),
            "failed_commands": [command["command"] for command in failed],
            "started_at": iso(started),
            "finished_at": iso(finished),
            "total_duration_seconds": round((finished - started).total_seconds(), 3),
        },
        "required_commands": REQUIRED_RELEASE_COMMANDS,
        "commands": commands,
    }


def load_report() -> dict[str, Any]:
    return json.loads(REPORT_JSON.read_text(encoding="utf-8"))


def validation_status() -> dict[str, Any]:
    if not REPORT_JSON.exists() or not REPORT_MD.exists():
        return {"valid": False, "reason": "candidate runtime verification files are missing"}
    try:
        payload = load_report()
    except Exception as exc:  # pragma: no cover - defensive status path
        return {"valid": False, "reason": f"could not read report: {exc}"}
    if payload.get("generated_by") != GENERATED_BY:
        return {"valid": False, "reason": "wrong generated_by marker"}
    if payload.get("command_manifest_sha256") != command_manifest_hash():
        return {"valid": False, "reason": "required command manifest is stale"}
    if payload.get("required_commands") != REQUIRED_RELEASE_COMMANDS:
        return {"valid": False, "reason": "required command list is stale"}
    current_snapshot = workspace_snapshot()
    recorded_snapshot = payload.get("workspace_snapshot", {})
    if recorded_snapshot.get("snapshot_sha256") != current_snapshot["snapshot_sha256"]:
        return {
            "valid": False,
            "reason": "workspace snapshot is stale",
            "recorded_snapshot_sha256": recorded_snapshot.get("snapshot_sha256"),
            "current_snapshot_sha256": current_snapshot["snapshot_sha256"],
        }
    commands = payload.get("commands", [])
    if len(commands) != len(REQUIRED_RELEASE_COMMANDS):
        return {"valid": False, "reason": "command count is stale"}
    for expected_index, (expected, command) in enumerate(
        zip(REQUIRED_RELEASE_COMMANDS, commands), start=1
    ):
        if command.get("index") != expected_index or command.get("command") != expected:
            return {"valid": False, "reason": f"command {expected_index} metadata is stale"}
        log_path = ROOT / str(command.get("log_path", ""))
        if not log_path.exists():
            return {"valid": False, "reason": f"missing command log: {command.get('log_path')}"}
        if sha256_file(log_path) != command.get("log_sha256"):
            return {"valid": False, "reason": f"command log hash is stale: {command.get('log_path')}"}
        if command.get("returncode") != 0 or not command.get("passed"):
            return {"valid": False, "reason": f"command failed: {expected}"}
    summary = payload.get("summary", {})
    if not summary.get("all_required_commands_passed"):
        return {"valid": False, "reason": "summary does not mark all commands passed"}
    return {
        "valid": True,
        "reason": "candidate runtime verification is current",
        "workspace_snapshot_sha256": current_snapshot["snapshot_sha256"],
        "command_count": len(REQUIRED_RELEASE_COMMANDS),
        "generated_at": payload.get("generated_at"),
        "total_duration_seconds": summary.get("total_duration_seconds"),
    }


def runtime_summary_for_matrix() -> dict[str, Any]:
    status = validation_status()
    payload: dict[str, Any] = {}
    if REPORT_JSON.exists():
        try:
            payload = load_report()
        except Exception:
            payload = {}
    summary = payload.get("summary", {}) if isinstance(payload, dict) else {}
    snapshot = payload.get("workspace_snapshot", {}) if isinstance(payload, dict) else {}
    return {
        "runtime_verification_present": bool(REPORT_JSON.exists() and REPORT_MD.exists()),
        "runtime_verification_current": bool(status.get("valid")),
        "runtime_verification_reason": status.get("reason", "unknown"),
        "runtime_verification_generated_at": payload.get("generated_at"),
        "runtime_verification_workspace_snapshot_sha256": snapshot.get("snapshot_sha256"),
        "runtime_verification_command_count": summary.get("command_count", len(REQUIRED_RELEASE_COMMANDS)),
        "runtime_verification_passed_count": summary.get("passed_count", 0),
        "runtime_verification_failed_count": summary.get("failed_count", len(REQUIRED_RELEASE_COMMANDS)),
        "runtime_verification_total_duration_seconds": summary.get("total_duration_seconds"),
        "all_required_commands_passed": bool(status.get("valid")),
    }


def write_report(payload: dict[str, Any]) -> None:
    DOCS.mkdir(exist_ok=True)
    REPORT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    summary = payload["summary"]
    lines = [
        "# Telomere Candidate Runtime Verification",
        "",
        f"Generated by `{GENERATED_BY}`.",
        "This artifact attaches fresh release-candidate command output. It runs no exploratory seed search, makes no compression claim, and does not by itself promote Telomere to production.",
        "",
        "## Summary",
        "",
        f"- Runtime status: `{summary['runtime_status']}`",
        f"- All required commands passed: `{summary['all_required_commands_passed']}`",
        f"- Commands: `{summary['passed_count']}` passed / `{summary['command_count']}` required",
        f"- Workspace snapshot: `{payload['workspace_snapshot']['snapshot_sha256']}`",
        f"- Snapshot file count: `{payload['workspace_snapshot']['file_count']}`",
        f"- Started at: `{summary['started_at']}`",
        f"- Finished at: `{summary['finished_at']}`",
        f"- Duration seconds: `{summary['total_duration_seconds']}`",
        "",
        "## Commands",
        "",
        "| # | passed | command | log |",
        "| ---: | --- | --- | --- |",
    ]
    for command in payload["commands"]:
        lines.append(
            f"| {command['index']} | `{command['passed']}` | `{command['command']}` | `{command['log_path']}` |"
        )
    lines.extend(
        [
            "",
            "## Failure Boundary",
            "",
            "- A passing artifact proves only that the listed commands passed on the recorded workspace snapshot.",
            "- It does not prove natural-corpus viability, real GPU acceleration, v2 format stability, or production readiness.",
            "- If any source file changes, rerun this script before using the artifact as release-candidate evidence.",
        ]
    )
    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def check_report() -> None:
    status = validation_status()
    if not status.get("valid"):
        raise SystemExit(status.get("reason", "candidate runtime verification is invalid"))
    text = REPORT_MD.read_text(encoding="utf-8")
    for phrase in (
        "Telomere Candidate Runtime Verification",
        "fresh release-candidate command output",
        "All required commands passed",
        "Workspace snapshot",
        "does not by itself promote Telomere to production",
    ):
        if phrase not in text:
            raise SystemExit(f"CANDIDATE_RUNTIME_VERIFICATION.md missing phrase: {phrase}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate saved runtime proof")
    parser.add_argument(
        "--status-json",
        action="store_true",
        help="print validation status JSON without raising on invalid artifacts",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.status_json:
        print(json.dumps(runtime_summary_for_matrix(), indent=2))
        return
    if args.check:
        check_report()
        return
    payload = build_report(run_commands=True)
    write_report(payload)
    if not payload["summary"]["all_required_commands_passed"]:
        raise SystemExit("candidate runtime verification failed")


if __name__ == "__main__":
    main()
