#!/usr/bin/env python3
"""Generate docs/sweeps.json and docs/SWEEPS.md from parameter sweeps."""

from __future__ import annotations

import argparse
import ctypes
import hashlib
import json
import os
import subprocess
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import generate_results


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
MEMORY_LIMIT = "100%"
TELEMETRY_LIMIT = "256"
STRUCTURED_JSON_LEN = len(generate_results.structured_json_bytes())
TWO_BYTE_SEED = b"\x01\x00"


SWEEP_MATRIX: list[dict[str, Any]] = []

for span_len in (4, 8, 12, 16, 20):
    SWEEP_MATRIX.append(
        {
            "name": f"span-{span_len}",
            "group": "span-length",
            "corpus": "planted-span",
            "span_len": span_len,
            "input_bytes": 1024,
            "offset": 0,
            "density_bytes": None,
            "passes": 1,
            "block_size": 4,
            "max_span_len": span_len,
            "hasher": "sha256",
            "note": "Planted one-seed spans at the requested length.",
        }
    )

for density_bytes in (0, 64, 128, 256, 512, 768, 1024):
    SWEEP_MATRIX.append(
        {
            "name": f"density-{density_bytes}",
            "group": "planted-density",
            "corpus": "planted-density",
            "span_len": 8,
            "input_bytes": 1024,
            "offset": 0,
            "density_bytes": density_bytes,
            "passes": 1,
            "block_size": 4,
            "max_span_len": 8,
            "hasher": "sha256",
            "note": "Contiguous planted generated bytes followed by deterministic filler.",
        }
    )

for input_bytes in (
    1024,
    4096,
    16_384,
    65_536,
    262_144,
    1_048_576,
    4_194_304,
    8_388_608,
    16_777_216,
):
    SWEEP_MATRIX.append(
        {
            "name": f"scale-density50-{input_bytes}",
            "group": "memory-scaling",
            "corpus": "planted-density",
            "span_len": 8,
            "input_bytes": input_bytes,
            "offset": 0,
            "density_bytes": input_bytes // 2,
            "passes": 1,
            "block_size": 4,
            "max_span_len": 8,
            "hasher": "sha256",
            "note": "50% planted generated bytes at increasing input sizes.",
        }
    )

for offset in (0, 1, 2, 3):
    for passes in (1, 2, 3, 4):
        SWEEP_MATRIX.append(
            {
                "name": f"offset-{offset}-passes-{passes}",
                "group": "recursive-offset",
                "corpus": "planted-offset",
                "span_len": 8,
                "input_bytes": 1024 + offset,
                "offset": offset,
                "density_bytes": None,
                "passes": passes,
                "block_size": 4,
                "max_span_len": 8,
                "hasher": "sha256",
                "note": "Generated spans shifted by prefix bytes to test pass-created alignment.",
            }
        )

for offset in (1, 2, 3):
    SWEEP_MATRIX.append(
        {
            "name": f"offset-{offset}-span-step-1",
            "group": "span-step",
            "corpus": "planted-offset",
            "span_len": 8,
            "input_bytes": 1024 + offset,
            "offset": offset,
            "density_bytes": None,
            "passes": 1,
            "block_size": 4,
            "span_step": 1,
            "max_span_len": 8,
            "hasher": "sha256",
            "note": "Generated spans shifted by sub-block prefix bytes, searched with byte-step starts.",
        }
    )

for max_span_len, span_step, passes in ((8, 4, 1), (8, 1, 1), (16, 1, 1), (16, 1, 2)):
    SWEEP_MATRIX.append(
        {
            "name": f"structured-json-span{max_span_len}-step{span_step}-pass{passes}",
            "group": "structured-search",
            "corpus": "structured-json",
            "span_len": max_span_len,
            "input_bytes": STRUCTURED_JSON_LEN,
            "offset": 0,
            "density_bytes": None,
            "passes": passes,
            "block_size": 4,
            "span_step": span_step,
            "max_span_len": max_span_len,
            "hasher": "sha256",
            "note": "Generated non-planted structured JSON searched with varied span windows and candidate start steps.",
        }
    )

for seed_depth in (1, 2):
    SWEEP_MATRIX.append(
        {
            "name": f"seed2-planted-depth{seed_depth}",
            "group": "seed-depth",
            "corpus": "planted-seed2",
            "span_len": 8,
            "input_bytes": 1024,
            "offset": 0,
            "density_bytes": None,
            "passes": 1,
            "block_size": 4,
            "max_span_len": 8,
            "hasher": "sha256",
            "seed_depth": seed_depth,
            "note": "Planted 8-byte spans generated from a two-byte seed, used to isolate seed-depth economics.",
        }
    )

SWEEP_MATRIX.append(
    {
        "name": "structured-json-depth2-span8-step1-pass1",
        "group": "seed-depth",
        "corpus": "structured-json",
        "span_len": 8,
        "input_bytes": STRUCTURED_JSON_LEN,
        "offset": 0,
        "density_bytes": None,
        "passes": 1,
        "block_size": 4,
        "span_step": 1,
        "max_span_len": 8,
        "hasher": "sha256",
        "seed_depth": 2,
        "note": "Generated non-planted structured JSON searched at seed depth 2 with byte-step starts.",
    }
)

for case in SWEEP_MATRIX:
    case.setdefault("seed_depth", 1)
    case.setdefault("span_step", case["block_size"])


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )


class ProcessMemoryCounters(ctypes.Structure):
    _fields_ = [
        ("cb", ctypes.c_ulong),
        ("PageFaultCount", ctypes.c_ulong),
        ("PeakWorkingSetSize", ctypes.c_size_t),
        ("WorkingSetSize", ctypes.c_size_t),
        ("QuotaPeakPagedPoolUsage", ctypes.c_size_t),
        ("QuotaPagedPoolUsage", ctypes.c_size_t),
        ("QuotaPeakNonPagedPoolUsage", ctypes.c_size_t),
        ("QuotaNonPagedPoolUsage", ctypes.c_size_t),
        ("PagefileUsage", ctypes.c_size_t),
        ("PeakPagefileUsage", ctypes.c_size_t),
    ]


def peak_working_set_bytes(proc: subprocess.Popen[str]) -> int | None:
    if os.name != "nt" or not hasattr(proc, "_handle"):
        return None
    counters = ProcessMemoryCounters()
    counters.cb = ctypes.sizeof(ProcessMemoryCounters)
    ok = ctypes.windll.psapi.GetProcessMemoryInfo(
        int(proc._handle),
        ctypes.byref(counters),
        counters.cb,
    )
    if not ok:
        return None
    return int(counters.PeakWorkingSetSize)


def run_measured(cmd: list[str]) -> tuple[subprocess.CompletedProcess[str], int | None]:
    proc = subprocess.Popen(
        cmd,
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    stdout, stderr = proc.communicate()
    peak = peak_working_set_bytes(proc)
    completed = subprocess.CompletedProcess(cmd, proc.returncode, stdout, stderr)
    if proc.returncode != 0:
        raise subprocess.CalledProcessError(
            proc.returncode,
            cmd,
            output=stdout,
            stderr=stderr,
        )
    return completed, peak


def sweep_manifest() -> list[dict[str, Any]]:
    fields = (
        "name",
        "group",
        "corpus",
        "span_len",
        "input_bytes",
        "offset",
        "density_bytes",
        "passes",
        "block_size",
        "seed_depth",
        "span_step",
        "max_span_len",
        "hasher",
        "note",
    )
    return [{field: case[field] for field in fields} for case in SWEEP_MATRIX]


def sweep_manifest_hash() -> str:
    payload = json.dumps(sweep_manifest(), sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def case_by_name(name: str) -> dict[str, Any]:
    for case in SWEEP_MATRIX:
        if case["name"] == name:
            return case
    raise KeyError(name)


def write_sweep_input(case: dict[str, Any], temp: Path) -> Path:
    path = temp / f"{case['name']}.bin"
    span = generate_results.planted_span(case["span_len"])
    input_bytes = int(case["input_bytes"])

    match case["corpus"]:
        case "planted-span":
            repetitions = input_bytes // len(span)
            data = (span * repetitions)[:input_bytes]
            data += generate_results.deterministic_bytes(case["name"], input_bytes - len(data))
        case "planted-density":
            planted_len = int(case["density_bytes"] or 0)
            planted_len -= planted_len % len(span)
            data = (span * (planted_len // len(span)))[:planted_len]
            data += generate_results.deterministic_bytes(case["name"], input_bytes - len(data))
        case "planted-offset":
            offset = int(case["offset"])
            prefix = bytes((0xA0 + idx) & 0xFF for idx in range(offset))
            data = prefix
            data += span * ((input_bytes - len(prefix)) // len(span))
            data = data[:input_bytes]
        case "planted-seed2":
            depth2_span = hashlib.sha256(TWO_BYTE_SEED).digest()[: case["span_len"]]
            repetitions = input_bytes // len(depth2_span)
            data = (depth2_span * repetitions)[:input_bytes]
            data += generate_results.deterministic_bytes(case["name"], input_bytes - len(data))
        case "structured-json":
            data = generate_results.structured_json_bytes()
        case _:
            raise ValueError(case["corpus"])

    path.write_bytes(data)
    return path


def summarize_telemetry(summary: dict[str, Any]) -> dict[str, Any]:
    telemetry = summary.get("engine_telemetry", {})
    layers = telemetry.get("layers", [])
    tiers = telemetry.get("tiers", [])
    tier_estimated_bytes = [
        tier.get("estimated_target_table_bytes", 0) for tier in tiers
    ]
    tier_estimated_total = sum(tier_estimated_bytes)
    return {
        "candidate_count": telemetry.get("candidate_count", 0),
        "selected_count": telemetry.get("selected_count", 0),
        "literal_bytes": telemetry.get("literal_bytes", 0),
        "bundle_count": telemetry.get("bundle_count", 0),
        "seeds_scanned": telemetry.get("seeds_scanned", 0),
        "seed_expansions": telemetry.get("seed_expansions", 0),
        "tier_count": len(tiers),
        "tier_lookup_count_total": sum(tier.get("lookup_count", 0) for tier in tiers),
        "tier_target_windows_total": sum(
            tier.get("target_windows", 0) for tier in tiers
        ),
        "tier_unique_spans_total": sum(tier.get("unique_spans", 0) for tier in tiers),
        "tier_estimated_target_table_bytes_total": tier_estimated_total,
        "tier_estimated_target_table_bytes_max": max(tier_estimated_bytes, default=0),
        "tier_estimated_target_table_mib_total": round(
            tier_estimated_total / (1024 * 1024), 3
        ),
        "candidate_hits_raw_total": sum(
            tier.get("candidate_hits_raw", 0) for tier in tiers
        ),
        "candidate_hits_profitable_total": sum(
            tier.get("candidate_hits_profitable", 0) for tier in tiers
        ),
        "layer_count": len(layers),
        "layer_payload_bytes": [layer.get("payload_bytes", 0) for layer in layers],
        "layer_selected_counts": [layer.get("selected_count", 0) for layer in layers],
        "stop_reason": telemetry.get("stop_reason", ""),
        "container_bytes": telemetry.get("container_bytes", 0),
    }


def run_sweep_case(case: dict[str, Any], temp: Path, exe: Path) -> dict[str, Any]:
    input_path = write_sweep_input(case, temp)
    output_path = temp / f"{case['name']}.tlmr"
    restored_path = temp / f"{case['name']}.restored"

    compress_cmd = [
        str(exe),
        "compress",
        str(input_path),
        str(output_path),
        "--engine",
        "streaming",
        "--format",
        "v2",
        "--hasher",
        case["hasher"],
        "--block-size",
        str(case["block_size"]),
        "--span-step",
        str(case["span_step"]),
        "--seed-depth",
        str(case["seed_depth"]),
        "--passes",
        str(case["passes"]),
        "--max-span-len",
        str(case["max_span_len"]),
        "--memory-limit",
        MEMORY_LIMIT,
        "--json",
        "--telemetry-limit",
        TELEMETRY_LIMIT,
        "--verify",
        "--force",
    ]

    t0 = time.perf_counter()
    proc, peak_memory_bytes = run_measured(compress_cmd)
    compress_ms = round((time.perf_counter() - t0) * 1000, 3)
    summary = json.loads(proc.stdout)

    t0 = time.perf_counter()
    run([str(exe), "decompress", str(output_path), str(restored_path), "--force"])
    decompress_ms = round((time.perf_counter() - t0) * 1000, 3)
    if restored_path.read_bytes() != input_path.read_bytes():
        raise RuntimeError(f"{case['name']}: decompressed bytes did not match input")

    input_bytes = input_path.stat().st_size
    output_bytes = output_path.stat().st_size
    telemetry = summarize_telemetry(summary)
    return {
        "name": case["name"],
        "group": case["group"],
        "span_len": case["span_len"],
        "span_step": case["span_step"],
        "offset": case["offset"],
        "density_bytes": case["density_bytes"],
        "passes": case["passes"],
        "seed_depth": case["seed_depth"],
        "input_sha256": hashlib.sha256(input_path.read_bytes()).hexdigest(),
        "output_sha256": hashlib.sha256(output_path.read_bytes()).hexdigest(),
        "input_bytes": input_bytes,
        "output_bytes": output_bytes,
        "delta_bytes": output_bytes - input_bytes,
        "delta_pct": ((output_bytes - input_bytes) / input_bytes * 100.0)
        if input_bytes
        else 0.0,
        "compress_ms": compress_ms,
        "throughput_mib_s": round(
            (input_bytes / (1024 * 1024)) / (compress_ms / 1000), 3
        )
        if compress_ms > 0
        else 0.0,
        "decompress_ms": decompress_ms,
        "memory_limit": MEMORY_LIMIT,
        "peak_memory_bytes": peak_memory_bytes,
        "peak_memory_mib": round(peak_memory_bytes / (1024 * 1024), 3)
        if peak_memory_bytes is not None
        else None,
        "telemetry": telemetry,
    }


def write_sweeps(cases: list[dict[str, Any]], results: list[dict[str, Any]]) -> None:
    payload = {
        "generated_by": "scripts/generate_sweeps.py",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "format_version": 1,
        "sweep_manifest_sha256": sweep_manifest_hash(),
        "sweep_matrix": sweep_manifest(),
        "selected_case_names": [case["name"] for case in cases],
        "environment": generate_results.environment_metadata(),
        "results": results,
    }
    (DOCS / "sweeps.json").write_text(json.dumps(payload, indent=2) + "\n")

    lines = [
        "# Telomere Sweep Results",
        "",
        "Generated by `scripts/generate_sweeps.py` from real release-binary CLI runs.",
        "This file is for curve-finding experiments; keep headline release claims in `docs/RESULTS.md`.",
        "",
        f"Sweep manifest SHA-256: `{sweep_manifest_hash()}`.",
        "",
        "| case | group | span | step | seed depth | offset | planted bytes | passes | input bytes | output bytes | delta bytes | delta | selected | layer selected | stop | compress ms | MiB/s | peak MiB | memory limit |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | ---: | ---: | ---: | --- |",
    ]
    for row in results:
        planted = row["density_bytes"] if row["density_bytes"] is not None else "-"
        layer_selected = ",".join(str(v) for v in row["telemetry"]["layer_selected_counts"])
        display_row = dict(row)
        display_row["peak_memory_mib"] = (
            row["peak_memory_mib"] if row["peak_memory_mib"] is not None else "-"
        )
        lines.append(
            "| {name} | {group} | {span_len} | {span_step} | {seed_depth} | {offset} | {planted} | {passes} | {input_bytes} | {output_bytes} | "
            "{delta_bytes:+} | {delta_pct:+.2f}% | {selected_count} | {layer_selected} | {stop_reason} | {compress_ms} | {throughput_mib_s} | {peak_memory_mib} | {memory_limit} |".format(
                planted=planted,
                selected_count=row["telemetry"]["selected_count"],
                layer_selected=layer_selected,
                stop_reason=row["telemetry"]["stop_reason"],
                **display_row,
            )
        )

    memory_rows = [row for row in results if row["group"] == "memory-scaling"]
    if memory_rows:
        lines.extend(
            [
                "",
                "## Work/Memory Accounting",
                "",
                "This table keeps the scale-performance stop rule auditable: measured peak memory should stay explainable by search-work and target-table telemetry, not just selected-span counts.",
                "",
                "| case | input bytes | selected | seed expansions | target windows | lookups | raw hits | profitable hits | est table MiB | peak MiB | peak/est |",
                "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
            ]
        )
        for row in memory_rows:
            telemetry = row["telemetry"]
            estimated_mib = telemetry["tier_estimated_target_table_mib_total"]
            peak_mib = row["peak_memory_mib"]
            peak_to_estimate = (
                round(peak_mib / estimated_mib, 3)
                if peak_mib is not None and estimated_mib > 0
                else "-"
            )
            display_peak_mib = peak_mib if peak_mib is not None else "-"
            lines.append(
                "| {name} | {input_bytes} | {selected_count} | {seed_expansions} | {target_windows} | {lookups} | {raw_hits} | {profitable_hits} | {estimated_mib} | {peak_mib} | {peak_to_estimate} |".format(
                    name=row["name"],
                    input_bytes=row["input_bytes"],
                    selected_count=telemetry["selected_count"],
                    seed_expansions=telemetry["seed_expansions"],
                    target_windows=telemetry["tier_target_windows_total"],
                    lookups=telemetry["tier_lookup_count_total"],
                    raw_hits=telemetry["candidate_hits_raw_total"],
                    profitable_hits=telemetry["candidate_hits_profitable_total"],
                    estimated_mib=estimated_mib,
                    peak_mib=display_peak_mib,
                    peak_to_estimate=peak_to_estimate,
                )
            )

    lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "- The span-length sweep isolates the v2 fixed-record overhead threshold: 4-byte spans cannot be emitted profitably, while longer spans increasingly amortize the 5-byte seed-span record.",
            "- The density sweep estimates how much planted/generated material is needed before selected-span savings beat v2 container and literal overhead.",
            "- The memory-scaling sweep keeps planted density fixed at 50% while increasing input size, making throughput, target windows, seed expansions, lookup counts, estimated target-table bytes, and peak working set comparable across sizes.",
            "- The recursive-offset sweep checks whether a first literal layer can create a second-pass block-grid opportunity; this is useful evidence, not a general convergence claim.",
            "- The span-step sweep checks whether sub-block candidate starts can recover an offset generated span in the first pass; it trades a wider search grid for alignment sensitivity.",
            "- The structured-search sweep applies the same streaming engine to generated non-planted JSON under block-step, byte-step, longer-span, and recursive settings; negative results are evidence too.",
            "- The seed-depth sweep isolates a two-byte planted seed that depth 1 cannot find, then measures depth 2 on both that controlled fixture and the structured JSON control.",
            "- Random and binary controls remain in `docs/RESULTS.md`; this sweep intentionally focuses on mechanism curves plus structured-search falsification.",
        ]
    )
    (DOCS / "SWEEPS.md").write_text("\n".join(lines) + "\n")


def check_sweeps() -> None:
    sweeps_path = DOCS / "sweeps.json"
    sweeps_md = DOCS / "SWEEPS.md"
    if not sweeps_path.exists() or not sweeps_md.exists():
        raise SystemExit("generated sweep files are missing")
    payload = json.loads(sweeps_path.read_text(encoding="utf-8"))
    if payload.get("generated_by") != "scripts/generate_sweeps.py":
        raise SystemExit("sweeps.json has wrong generated_by marker")
    if payload.get("sweep_manifest_sha256") != sweep_manifest_hash():
        raise SystemExit("sweeps.json sweep manifest hash is stale")
    expected_names = [case["name"] for case in SWEEP_MATRIX]
    result_names = [result["name"] for result in payload.get("results", [])]
    if result_names != expected_names:
        raise SystemExit("sweeps.json does not contain the full default sweep matrix")
    required_telemetry = {
        "seeds_scanned",
        "seed_expansions",
        "tier_count",
        "tier_lookup_count_total",
        "tier_target_windows_total",
        "tier_unique_spans_total",
        "tier_estimated_target_table_bytes_total",
        "tier_estimated_target_table_bytes_max",
        "candidate_hits_raw_total",
        "candidate_hits_profitable_total",
    }
    for result in payload.get("results", []):
        telemetry = result.get("telemetry", {})
        missing_keys = sorted(required_telemetry.difference(telemetry))
        if missing_keys:
            raise SystemExit(
                f"{result.get('name', '<unknown>')} missing sweep telemetry: {', '.join(missing_keys)}"
            )
    text = sweeps_md.read_text(encoding="utf-8")
    missing = [name for name in expected_names if name not in text]
    if missing:
        raise SystemExit(f"SWEEPS.md missing cases: {', '.join(missing)}")
    for phrase in (
        "Work/Memory Accounting",
        "seed expansions",
        "target windows",
        "estimated target-table bytes",
        "peak/est",
    ):
        if phrase not in text:
            raise SystemExit(f"SWEEPS.md missing scale telemetry phrase: {phrase}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", action="append", help="run one named sweep case; repeatable")
    parser.add_argument("--list", action="store_true", help="list sweep case names and exit")
    parser.add_argument("--manifest-sha", action="store_true", help="print sweep manifest hash and exit")
    parser.add_argument("--check", action="store_true", help="validate checked-in generated sweeps without running them")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.list:
        for case in SWEEP_MATRIX:
            print(case["name"])
        return
    if args.manifest_sha:
        print(sweep_manifest_hash())
        return
    if args.check:
        check_sweeps()
        return

    if args.case:
        try:
            cases = [case_by_name(name) for name in args.case]
        except KeyError as exc:
            raise SystemExit(f"unknown sweep case: {exc.args[0]}") from exc
    else:
        cases = SWEEP_MATRIX

    exe = generate_results.build_release_binary()
    with tempfile.TemporaryDirectory() as tmp:
        temp = Path(tmp)
        results = [run_sweep_case(case, temp, exe) for case in cases]
    write_sweeps(cases, results)


if __name__ == "__main__":
    main()
