name: Full CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
        mode: [debug, release]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: fmt check
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: cargo deny
        run: |
          cargo install cargo-deny --locked
          cargo deny check
      - name: tests
        run: |
          if [ "${{ matrix.mode }}" = "release" ]; then
            cargo test --release --all -- --nocapture
          else
            cargo test --all -- --nocapture
          fi
      - name: performance benchmark
        if: matrix.rust == 'stable' && matrix.mode == 'release'
        run: scripts/perf_check.sh
      - name: size check
        if: matrix.rust == 'stable' && matrix.mode == 'release'
        run: scripts/size_check.sh
      - uses: actions/upload-artifact@v4
        if: matrix.rust == 'stable' && matrix.mode == 'release'
        with:
          name: artifacts-${{ matrix.rust }}-${{ matrix.mode }}
          path: target/artifacts/telomere.gz
